# Required
sonar.projectKey=LacusFaustus_NOTIFICATION-SERVICE
sonar.organization=lacusfaustus
sonar.host.url=https://sonarcloud.io

# Project settings
sonar.projectName=notification-service
sonar.projectVersion=1.0.0

# Source and test directories
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.source=17

# Coverage
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclusions
sonar.coverage.exclusions=**/entity/**,**/dto/**,**/config/**,**/exception/**,**/model/**
sonar.exclusions=**/generated-*,**/target/**

# Quality Gate timeout
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
